FROM golang:1.23-alpine

ENV TZ=America/Argentina/Buenos_Aires

RUN apk add --no-cache \
    tzdata \
    sqlite \
    sqlite-dev \
    gcc \
    musl-dev

WORKDIR /app

COPY . .

RUN go mod download && go mod verify

RUN CGO_ENABLED=1 GOOS=linux go build -o /app/tmp/customers_manager \
    ./projects/customers-manager/cmd/api/main.go

EXPOSE 8080

CMD ["/app/tmp/customers_manager"]